version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: covidiometro
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data